package com.invitation.module.common.logger;

public enum LoggerType {

    DETAIL_LOGGER_ERROR, DETAIL_LOGGER_WARN, DETAIL_LOGGER_INFO, DETAIL_LOGGER_DEBUG, DETAIL_LOGGER_TRACE
    ,REQRECV_LOGGER_ERROR, REQRECV_LOGGER_WARN, REQRECV_LOGGER_INFO, REQRECV_LOGGER_DEBUG, REQRECV_LOGGER_TRACE
}
